//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAction
    {
        public int RoleActionId { get; set; }
        public int RoleId { get; set; }
        public int ActionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Role Role { get; set; }
    }
}
